// <auto-generated />
using System;
using EFGetStarted;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFGetStarted.LatencyMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentile")
                        .HasColumnType("float");

                    b.Property<long?>("TestRunId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestRunId");

                    b.ToTable("LatencyMetrics");
                });

            modelBuilder.Entity("EFGetStarted.PullRequest", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PullRequests");
                });

            modelBuilder.Entity("EFGetStarted.PullRequestBuildInfo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ContainerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PullRequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("EFGetStarted.TestRun", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("BuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PullRequestBuildInfoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PullRequestId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PullRequestBuildInfoId");

                    b.HasIndex("PullRequestId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("EFGetStarted.LatencyMetric", b =>
                {
                    b.HasOne("EFGetStarted.TestRun", null)
                        .WithMany("LatencyMetrics")
                        .HasForeignKey("TestRunId");
                });

            modelBuilder.Entity("EFGetStarted.PullRequestBuildInfo", b =>
                {
                    b.HasOne("EFGetStarted.PullRequest", "PullRequest")
                        .WithMany("Builds")
                        .HasForeignKey("PullRequestId");
                });

            modelBuilder.Entity("EFGetStarted.TestRun", b =>
                {
                    b.HasOne("EFGetStarted.PullRequestBuildInfo", null)
                        .WithMany("TestRuns")
                        .HasForeignKey("PullRequestBuildInfoId");

                    b.HasOne("EFGetStarted.PullRequest", "PullRequest")
                        .WithMany()
                        .HasForeignKey("PullRequestId");
                });
#pragma warning restore 612, 618
        }
    }
}
